print("******welcomeṭo agency ticket booking*****")
print("1.aeroplane__tnagency")
print("2.tn_bus_agency")
print("3.tn_train agency")
print("4.tn_ship_agency")
print("5.nv_bus_agency")
print("6.k_aeroplane _agency")
print("7.k_ship_agency")
print("8.k_train_agency")
print("9.k _bus_agency")   
def aeroplane_tn_agency(place): 
 if place=="dubai":
    print("8 days package at the last of every month")
    print("onnly 8 days rupees is 70,000 in per person")
    print("If you want to more days to stay in dubai our company worker stay with you to guide you")
    print("stay more than the provided days ,the amount is 7,000 per day it is include the our worker payment")
    print("must bring the visa ,passport")
    print("your luggages are always safe ")
    print("manitory things are visa,passport,id proof")
    print("IN TRAVEL COMPULSORY YOU HAVING THE CORONA INJECTION CERTIFICATE")
    print("MUST WEAR MASK AND HAND CLOWSE DURING TRAVEL")
    print("YOU SHOULD COME WITH AT THE PROPER TIME BEFORE THE TIMINING")
    print("YOU MUST HAVE ANY PROOF LIKE AADHAR CARD,VOTER ID,PAN CARD\n YOU MUST HAVE ONLY ONE PROOF BUT ITS COMPULSORY")
    print("@@@@@opinionsection@@@@@@@")
    print("done or cancelled")
    opinion=(input("enter your opinion:")).upper()
    if opinion=="DONE":
       print("thank you so much for using our agency")
       print("please pay the amount directly sir or mam")
       print("some time online payment is not working")
       print("other wise you wise the online payment option")
       process=input("enter your card type:")
       if process=="rupay":
         print("there no due to use rupay card for particular bank")
         print("icic,sbi,these bank only put no due to pay the amount")
       elif process=="credit card":
         print("10 rupees due charges will be provided")
    elif opinion=="CANCELLED":
       print("thank you for using our shop")
 elif place=="america":
    print("5 days package at the last of every month")
    print("only 5 days rupees is 90,000 in per person")
    print("If you want to more days to stay in dubai our company worker stay with you to guide you")
    print("stay more than the provided days ,the amount is 10,000 per day it is include the our worker payment")
    print("must bring the visa ,passport")
    print("your luggages are always safe ")
    print("manitory things are visa,passport,id proof")
    print("IN TRAVEL COMPULSORY YOU HAVING THE CORONA INJECTION CERTIFICATE")
    print("MUST WEAR MASK AND HAND CLOWSE DURING TRAVEL")
    print("YOU SHOULD COME WITH AT THE PROPER TIME BEFORE THE TIMINING")
    print("YOU MUST HAVE ANY PROOF LIKE AADHAR CARD,VOTER ID,PAN CARD\n YOU MUST HAVE ONLY ONE PROOF BUT ITS COMPULSORY")
    print("@@@@@opinionsection@@@@@@@")
    print("done or cancelled")
    opinion=(input("enter your opinion:")).upper()
    if opinion=="DONE":
       print("thank you so much for using our agency")
       print("please pay the amount directly in maximum sir or mam")
       print("because some time online payment is not working")
       print("other wise you wise the online payment option")
       process=input("enter your card type:")
       if process=="rupay":
         print("there no due to use rupay card for particular bank")
         print("icic,sbi,these bank only put no due to pay the amount")
       elif process=="credit card":
         print("10 rupees due charges will be provided")
    elif opinion=="CANCELLED":
       print("thank you for using our agency")
 elif place=="delhi":
    print("10 days package at the last of every month")
    print("only 10 days rupees is 50,000 in per person")
    print("If you want to more days to stay in dubai our company worker stay with you to guide you")
    print("stay more than the provided days ,the amount is 1,000 per day it is include the our worker payment")
    print("must bring the visa ,passport is not manitory")
    print("your luggages are always safe ")
    print("IN TRAVEL COMPULSORY YOU HAVING THE CORONA INJECTION CERTIFICATE")
    print("MUST WEAR MASK AND HAND CLOUSE DURING TRAVEL")
    print("YOU SHOULD COME WITH AT THE PROPER TIME BEFORE THE TIMINING")
    print("YOU MUST HAVE ANY PROOF LIKE AADHAR CARD,VOTER ID,PAN CARD\n YOU MUST HAVE ONLY ONE PROOF BUT ITS COMPULSORY")
    print("@@@@@opinionsection@@@@@@@")
    print("done or cancelled")
    opinion=(input("enter your opinion:")).upper()
    if opinion=="DONE":
       print("thank you so much for using our agency")
       print("please pay the amount directly sir or mam")
       print("some time online payment is not working")
       print("other wise you wise the online payment option")
       process=input("enter your card type:")
       if process=="rupay":
         print("there no due to use rupay card for particular bank")
         print("icic,sbi,these bank only put no due to pay the amount")
       elif process=="credit card":
         print("10 rupees due charges will be provided")
    elif opinion=="CANCELLED":
       print("thank you for using our agency")
 elif place=="africa":
    print("20 days package at the last of every month")
    print("only 20 days rupees is 90,000in per person")
    print("If you want to more days to stay in dubai our company worker stay with you to guide you")
    print("stay more than the provided days ,the amount is 9,000 per day it is include the our worker payment")
    print("must bring the visa ,passport is not manitory")
    print("your luggages are always safe")
    print("IN TRAVEL COMPULSORY YOU HAVING THE CORONA INJECTION CERTIFICATE")
    print("MUST WEAR MASK AND HAND CLOWSE DURING TRAVEL")
    print("YOU SHOULD COME WITH AT THE PROPER TIME BEFORE THE TIMINING")
    print("YOU MUST HAVE ANY PROOF LIKE AADHAR CARD,VOTER ID,PAN CARD\n YOU MUST HAVE ONLY ONE PROOF BUT ITS COMPULSORY")
def tn_bus_agency(area):
  if area=="madurai": 
    print("20 days package at the last of every month")
    print("only 20 days rupees is 10,000in per person")
    print("If you want to more days to stay in dubai our company worker stay with you to guide you")
    print("stay more than the provided days ,the amount is 200 per day it is include the our worker payment")
    print("only aadhar must haveduring the travel")
    print("your luggages are always safe ")
  elif area=="chennai": 
    print("10 days package at the last of every month")
    print("only 10 days rupees is 10,000in per person")
    print("If you want to more days to stay in dubai our company worker stay with you to guide you")
    print("stay more than the provided days ,the amount is 500 per day it is include the our worker payment")
    print("only aadhar must haveduring the travel")
    print("your luggages are always safe ")
def tn_train_agency(station):
  if station=="chennai":
    print("20 days package at the last of every month")
    print("only 20 days rupees is 10,000 in per person")
    print("If you want to more days to stay in dubai our company worker stay with you to guide you")
    print("stay more than the provided days ,the amount is 500 per day it is include the our worker payment")
    print("only aadhar must haveduring the travel")
    print("your luggages are always safe ")
  elif station=="thoothukudi":
    print("10 days package at the last of every month")
    print("only 10 days rupees is 5,000 in per person")
    print("If you want to more days to stay in dubai our company worker stay with you to guide you")
    print("stay more than the provided days ,the amount is 300 per day it is include the our worker payment")
    print("only aadhar must haveduring the travel")
    print("your luggages are always safe ")
print("##############hello cutomers############\n")
user=int(input("enter your number:"))
if user==1:
  print("dubai,america,delhi,africa")
  place=input("enter your area:").lower()
  aeroplane_tn_agency(place)
elif user==2:
  print("madurai,chennai")
  area=input("enter your area you want to go a small tour:")
  tn_bus_agency(area)
elif user==3:
  print("chennai,thoothukudi")
  station=input("enter your station:").lower()
  tn_train_agency(station)
else:
  print("thank you sry only few agency are available in now all other are in engaged ")